### ISSUE TITLE
have you added the walk then running feature ?

### ISSUE THREAD

**Issue by stickylabdev** [akashenen/2d-platformer-controller#2]
animations

**Comment by akashenen** [comment]
There is a basic animator logic where you can plug any animations you want, but I will try to find some free assets to add as an example :D

**Comment by akashenen** [comment]
I fixed some animation problems and added an example sprite! Right now it's not the best organized animator solution but it's working. @mr-tuduf check it out too!

**Comment by stickylabdev** [comment]
![image](https://user-images.githubusercontent.com/13078369/103421194-ad220980-4bcd-11eb-8f34-eccaed215d94.png)


igot this error ,when first time importing

**Comment by akashenen** [comment]
It looks like something to do with unity rendering pipelines. Try opening the package manager and updating the packages used in the project.
